#!/bin/bash

export ANDROID_NDK_HOME=$GITHUB_WORKSPACE/ndk

# "booo, bash feature!"
declare -A CMAKE_CONFIGURE_PLATFORM_OPTS

CMAKE_CONFIGURE_PLATFORM_OPTS[i386]=-DANDROID_ABI=x86
CMAKE_CONFIGURE_PLATFORM_OPTS[arm64]=-DANDROID_ABI=arm64-v8a
CMAKE_CONFIGURE_PLATFORM_OPTS[armel]=-DANDROID_ABI=armeabi-v7a

CMAKE_CONFIGURE_OPTS="-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_PLATFORM=21 ${CMAKE_CONFIGURE_PLATFORM_OPTS[$GH_CPU_ARCH]}"

USE_CMAKE=1

source scripts/gha/build_common.sh
