name: Build & Deploy HLSDK
on:
  push:
    branches:
      - master
  schedule:
    # Rebuild every two days at 03:17 UTC to pick up upstream hlsdk-portable changes
    - cron: '17 3 */2 * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            targetos: android
            targetarch: i386
          - os: ubuntu-latest
            targetos: android
            targetarch: arm64
          - os: ubuntu-latest
            targetos: android
            targetarch: armv7l
    env:
      YQ_VERSION: 4.52.5
      GH_CPU_OS: ${{ matrix.targetos }}
      GH_CPU_ARCH: ${{ matrix.targetarch }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: bash scripts/gha/${{ runner.environment }}/deps_${{ matrix.targetos }}.sh
    - name: Build HLSDK
      env:
        FWGS_PFX_PASSWORD: ${{ secrets.FWGS_PFX_PASSWORD }}
      run: bash scripts/gha/${{ runner.environment }}/build_${{ matrix.targetos }}.sh
    - name: Upload HLSDK (artifacts)
      uses: actions/upload-artifact@v4
      with:
        name: artifact-${{ matrix.targetos }}-${{ matrix.targetarch }}
        path: out/*
  release:
    name: "Upload releases"
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Remove old release, fetch artifacts, repackage binaries and upload new release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_TAG: ${{ github.ref_name == 'master' && 'continuous' || format('continuous-{0}', github.ref_name) }}
      run: |
        gh release delete "$RELEASE_TAG" \
          --yes \
          --cleanup-tag \
          --repo "$GITHUB_REPOSITORY" || true
        sleep 5s
        gh run download "$GITHUB_RUN_ID" \
          --dir out/ \
          --repo "$GITHUB_REPOSITORY"
        pushd out/
        echo "Found artifacts:"
        ls
        for i in $(find -mindepth 1 -maxdepth 1 -type d); do
          mv "$i"/* .
          rm -rf "$i"
        done
        echo "Repackaged artifacts:"
        ls -R
        popd
        python3 scripts/gha/generate_manifest.py
        sleep 5s
        gh release create "$RELEASE_TAG" \
          --title "HLSDK Mega Continuous ${{ github.ref_name }} Build" \
          --target $GITHUB_SHA \
          --repo "$GITHUB_REPOSITORY" \
          --prerelease
        gh release upload --clobber "$RELEASE_TAG" out/manifest.json
        for zipfile in out/*.zip; do
          if [ -f "$zipfile" ]; then
            gh release upload --clobber "$RELEASE_TAG" "$zipfile"
            sleep 5s
          fi
        done
